logging:
  pattern:
    console: "[Kafka Core Consumers %t] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 8081

spring:
  main:
    banner-mode: OFF
  profiles:
    active: local
  kafka:
    consumer:
      group-id: default-spring-consumer
      auto-offset-reset: earliest
  jackson:
    date-format: yyyy-MMM-dd